apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-etcd-storage-class
  namespace: etcd
#provisioner: kubernetes.io/no-provisioner
provisioner: dobs.csi.digitalocean.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: etcd
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 2
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: gcr.io/etcd-development/etcd:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        volumeMounts:
        - name: etcd-claim-template
          mountPath: /var/run/etcd
        command:
          - /bin/sh
          - -c
          - |
            echo ${HOSTNAME}
            PEERS="etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
            exec etcd --name ${HOSTNAME} \
              --listen-peer-urls http://0.0.0.0:2380 \
              --listen-client-urls http://0.0.0.0:2379 \
              --advertise-client-urls http://${HOSTNAME}.etcd:2379 \
              --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
              --initial-cluster-token etcd-cluster-1 \
              --initial-cluster ${PEERS} \
              --initial-cluster-state new \
              --data-dir /var/run/etcd/default.etcd
  volumeClaimTemplates:
  - metadata:
      name: etcd-claim-template
    spec:
      storageClassName: local-etcd-storage-class
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  namespace: etcd
spec:
  selector:
    app: etcd
  clusterIP: None
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
  - name: etcd-peer-port
    port: 2380
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-lb
  namespace: etcd
spec:
  type: LoadBalancer
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd