apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracardi-gui-deployment
  namespace: tracardi
  labels:
    app: tracardi-gui
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tracardi-gui
  template:
    metadata:
      labels:
        app: tracardi-gui
        tier: frontend
    spec:
      containers:
        - name: tracardi-gui
          image: tracardi/tracardi-gui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: gui-port

---
apiVersion: v1
kind: Service
metadata:
  name: tracardi-gui-nodeport
  namespace: tracardi
spec:
  type: NodePort
  selector:
    app: tracardi-gui
  ports:
    - protocol: TCP
      port: 8787
      targetPort: gui-port

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: tracardi-gui-ingress
#  namespace: tracardi
#  annotations:
#    kubernetes.io/ingress.class: "traefik"
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: tracardi-gui-service
#            port:
#              number: 8787