
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-redis-storage
  namespace: redis
#provisioner: kubernetes.io/no-provisioner
provisioner: dobs.csi.digitalocean.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv1
spec:
  storageClassName: local-redis-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/redis/pv1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv2
spec:
  storageClassName: local-redis-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/redis/pv2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-redis-pv3
spec:
  storageClassName: local-redis-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/redis/pv3"
