apiVersion: v1
kind: Service
metadata:
  name: elastic-svc-nodeport
  namespace: elastic
spec:
  selector:
    app: es-cluster
  ports:
  - name: http
    port: 9200
    targetPort: es-http
  type: NodePort